
language: python

services:
  - docker
  
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t stream4good/scrapping-robot-direct:$TRAVIS_BRANCH -f direct .
  - docker push stream4good/scrapping-robot-direct:$TRAVIS_BRANCH
